### ISSUE TITLE
Build error when using the python3.7 shipped with Xcode

### ISSUE THREAD

**Issue by Eerim** [ronaldoussoren/py2app#299]
Hi there,

When I tried to build for deployment I got an error. 

I typed the following command
python3 setup.py py2app

I got the following error(This is the last two lines of output). 

copying file /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python3 -> /Users/evrim/Desktop/code/WantedOutfits/dist/check_products.app/Contents/MacOS/python
error: [Errno 2] /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python3: 'No such file or directory' 

How can I fix this error?

Thank you in advance.

**Comment by ronaldoussoren** [comment]
That's because the packaging for the copy of Python 3 included in Xcode.app is slightly different than how upstream packages Python 3 in a framework.

A quick workaround is to copy "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python" to "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python3".
