### ISSUE TITLE
mac pro py2app packaged app must be open +a to run

### ISSUE THREAD

**Issue by rockmelodies** [ronaldoussoren/py2app#324]
How to perform functional tests on the packaged app, check command line errors or record error logs, etc.

**Comment by ronaldoussoren** [comment]
You can test like you test any other mac app. I usually test manually, but AFAIK there are GUI testing tools for mac (similar to selenium voor web testing).

One thing you can do to check for error messages is to start the application from the Terminal, for an application named "hello.app" the command to run is "dist/hello.app/Contents/MacOS/hello".    

In the past you could also check Console.app, but that no longer works reliably due to changes in the OS.
