### ISSUE TITLE
code security

### ISSUE THREAD

**Issue by rockmelodies** [ronaldoussoren/py2app#326]
Excuse me, if the encrypted code is used, it cannot be packaged successfully.
https://pyarmor.readthedocs.io/zh/latest/usage.html
Are there any good recommendations? The key is to protect code security

**Comment by ronaldoussoren** [comment]
Py2app does not have a way to encrypt or otherwise obfuscate python code.   This is a feature I don't need myself and I therefore have no recommendations on this.

I'd expect that you need a patched python interpreter to truly obfuscate the code, otherwise you can extract code objects through a debugger and use the usual tools to reconstruct source code.
