### ISSUE TITLE
APP dose not work after using 'moviepy'

### ISSUE THREAD

**Issue by door5719** [ronaldoussoren/py2app#338]
In macOS10.15 ，python3.7.3，I use  moviepy as  
...
from moviepy.editor import AudioFileClip 
....
and command line :python3   setup . py   py2app -A     to get the app,
the app works well.
But use command line :python3   setup . py   py2app , the generate application will not work with error

without the 'moviepy', get the app using 'python3   setup . py   py2app' will work well,what's wrong?

**Comment by ronaldoussoren** [comment]
What's the error you get when you run time application from the terminal, that is: given application "test.app" run "dist/test.app/Contents/MacOS/test" in the terminal. This will show any errors printed during startup in the terminal.

**Comment by ronaldoussoren** [comment]
I can reproduce using the example at "https://zulko.github.io/moviepy/examples/moving_letters.html".

```
  File "moviepy/config.pyc", line 36, in <module>
  File "/Users/ronald/Projects/py2app/examples/simple/dist/hello.app/Contents/Resources/lib/python3.9/imageio/plugins/ffmpeg.py", line 49, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "imageio_ffmpeg/_utils.pyc", line 29, in get_ffmpeg_exe
  File "pkg_resources/__init__.pyc", line 1130, in resource_filename
  File "pkg_resources/__init__.pyc", line 1730, in get_resource_filename
NotImplementedError: resource_filename() only supported for .egg, not .zip
```

I fixed that problem by adding a recipe for the "imageio_ffmpeg" python package. 

That said, I don't have ffmpeg on my machine and now get an error that ffmpeg cannot be found. Both inside and outside of a bundled app.

**Comment by ronaldoussoren** [comment]
Please test if the version in the repository fixes the issue for you.

Is it expected that I need to install ffmpeg manually to use this package? The website doesn't mention this.  If installing ffmpeg manual is expected you'll also have to arrange for adding those tools to the app bundle, otherwise the app still has a dependency on a locally installed copy of those tools (including ffmpeg as a resource file should do the trick, although you will have to configure MoviePy to look in the right location).
