### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ZCG-coder** [ronaldoussoren/py2app#341]
I made a Python 3 app, and I ran it using Python 3.9. I found that it has dark theme.  
<img width="1446" alt="Original" src="https://user-images.githubusercontent.com/76037593/112090896-54ac4800-8bcf-11eb-80ae-b92427d08e99.png">
Then I created a setup.py and ran: 
```
python3 setup.py py2app -A
```
I found that the dark theme is missing:  
  
<img width="1597" alt="Py2App" src="https://user-images.githubusercontent.com/76037593/112090900-55dd7500-8bcf-11eb-9cb4-e637f5c588f2.png">
  
Could you fix this?

**Comment by ronaldoussoren** [comment]
Either use the "universal2" installer on MacOS, or add a fragment to your setup.py file:

```
setup(
   ...
   options=dict(
     py2app=dict(
       plist=dict(
         NSRequiresAquaSystemAppearance=False
       )
     )
   )
)
```

This will add a key to the setup.py file to enable support for Dark Mode.  This is needed because the stub executables are compiled on a fairly old version of macOS.   I cannot recompile them at the moment because that would break support for Tkinter in the default macOS installer on Python.org.

I've added an entry about this to the py2app FAQ at https://py2app.readthedocs.io/en/latest/faq.html (I just committed the change, the text should end up at the site later today).
