### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by lberezinski** [ronaldoussoren/py2app#346]
Hello, I'm using py2app for the first time I'm encountering this error `Fatal Python error: PyThreadState_Get: no current thread` when I'm running the app (the issue does not happen when I run it regularly i.e. using python3.6). This error happens when I import the following library `https://pypi.org/project/cos-aspera/` | `from ibm_s3transfer.aspera.manager import AsperaConfig`

I'm using python 3.6.0.

Please help me troubleshoot this.

Thanks

**Comment by ronaldoussoren** [comment]
That's weird. I don't know what's going on and cannot debug at the moment because I don't have Python 3.6 on my development machine.

I do note that this package hasn't seen updates since 2018 and refers to a website with an expired website on PyPI. I strongly advise to use some other package, this may have been a valid package but shows all signs of abandonware.
