### ISSUE TITLE
packaging and running sentencepiece breaks application

### ISSUE THREAD

**Issue by PJ-Finlay** [ronaldoussoren/py2app#350]
I'm attempting to bundle [Argos Translate](https://github.com/argosopentech/argos-translate) for macOS. Installing from PyPI with pip works and bundling with py2app successfully completes but the application fails to start. 

I've narrowed down the issue to bundling [Sentence Piece](https://github.com/google/sentencepiece), and the issue can be replicated by adding `sentencepiece==0.1.94` to `requirements.txt` and `import sentencepiece` to `my_application.py` in [this starter code](https://github.com/PJ-Finlay/pyqt-starter/tree/e6c015029bfe5d513fd30c2164be3346f17b4dbf).

I'm unable to find any logs that seem related in either the py2app build or system logs.

Any help appreciated!

**Comment by ronaldoussoren** [comment]
One thing to do when debugging application start failures is to start the application from the command-line. That is, for an application named *MyApp* run ``MyApp.app/Contents/MacOS/MyApp``.  This will print any errors to the terminal, instead of them being eaten by the system.

Sadly enough getting this information from the system logs is nearly impossible with more recent versions of macOS, even with code in py2app that explicitly redirects stdout/stderr to system logs.

**Comment by ronaldoussoren** [comment]
py2app does support extensions.  It looks like sentencepiece uses Swig and that's a know cause for headaches on my end due to the way that tool is structured.

Could you check if changing OPTIONS in setup.py to the definition below helps:

```
OPTIONS = { "packages": [ "sentencepiece" ] }
```

This will include that entire package without trying to optimise it for size.

I'll see if I can reproduce the problem on my end as well and teach py2app how to handle this package correctly.

**Comment by PJ-Finlay** [comment]
`OPTIONS = { "packages": [ "sentencepiece" ] }` in `setup.py` fixes the issue thanks!
