### ISSUE TITLE
Tkinter windows display as a black window

### ISSUE THREAD

**Issue by ShadowDust99** [ronaldoussoren/py2app#374]
Packaging using py2app 0.26 seems to render Tkinter windows as black. Elements in my code are arranged using Tkinter's pack method.

Currently running Python 3.9.6 (v3.9.6:db3ff76da1), tk 0.1.0 (according to pip3) and Tkinter version 8.6

Let me know if you need any further information, I'm still pretty new to Python.

**Comment by ronaldoussoren** [comment]
How did you install Python? Did you use an installer on python.org or some other method?  

If you did use the installer on python.org: did you use the "Universal 2" or "Intel" variant? If in doubt: what's the output of: ```import os; os.system(f"file {sys.executable}")```?

And finally: What version of macOS are you using?

**Comment by HoofedEar** [comment]
Hello, I am having a similar issue so I'm throwing my info in to help debug this!

The prepackaged version of Python 3.9 with macOS does not include tkinter, so I had to run the installer from python.org.
After I installed it, I was able to successfully run the example provided for tkinter (for use with py2app).

Now, when I use python3, tkinter imports properly, and the result of:
`import os, sys; os.system(f"file {sys.executable}")`
is
`/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: Mach-O 64-bit executable x86_64
0`

Version of macOS: 11.6

**Comment by ShadowDust99** [comment]
> How did you install Python? Did you use an installer on python.org or some other method?
> 
> If you did use the installer on python.org: did you use the "Universal 2" or "Intel" variant? If in doubt: what's the output of: `import os; os.system(f"file {sys.executable}")`?
> 
> And finally: What version of macOS are you using?

I had Python 3 installed via command line initially, but after seeing @HoofedEar response, I installed Python 3 using the Intel installer from python.org. Still experiencing the same issue.

`import os, sys; os.system(f"file {sys.executable}")`
returns
```
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: Mach-O 64-bit executable x86_64
0
```
Currently running macOS 11.6

**Comment by HoofedEar** [comment]
@ShadowDust99 I think I figured it out
On python.org's download page, there are two different options for installers, an "Intel" one and a "Universal 2" one.

I downloaded and installed the Universal 2 version, and after installing and running 
`python3 setup.py py2app`
It worked perfectly with the provided tkinter example :)

**Comment by ronaldoussoren** [comment]
Thanks for the feedback.  I thought I had tested with the "Intel" variant of the installer, but it looks like I only tested with the "Universal 2" one (which should "just work"), although you may run into problems with package availability when installing wheels from PyPI when you're using an M1 Mac (because there is a significant amount of projects that do not yet have arm64 wheels for macOS available, mostly due to lack of cloud CI/CD systems that can be used to test such wheels).

On an Intel Mac the Universal 2 installer should be the better option for all users, on M1 Mac's the availability of wheels complicates things a little (but even then: there is a python3-intel64 binary that will work fine with intel-only wheels).

Some technical background on the problem:
* macOS uses the SDK used to compile the main executable in an application to check if backward compatibility code should be used, in particular for dark mode support.
* The main executable in apps build using py2app is a binary supplied by py2app. That binary is compiled on a macOS 11 system with Xcode 12, and as such the system thinks that the app  is modern and doesn't need backward compatibility mode. 
* The "Intel" variant of the python.org installer is build on macOS 10.9 and includes a relatively old version of Tcl/Tk, and because of that is not compatible with dark-mode support
* The "Universal 2" variant of the installer is build on macOS 11 and includes the latest stable version of Tcl/Tk, and is compatible with dark-mode support

I've tried to detect the old Tk version in py2app, and use an old version of the main executable for those applications. But that obviously doesn't work as expected :-(.

**Comment by ronaldoussoren** [comment]
I'll push out a release tonight.  The actual problem was a lot simpler than expected, the code itself was OK but the old version of the main executable was not included in distribution archives.
